// Generated by https://quicktype.io

export interface IProdudctDetails {
    author: Author;
    item:   Item;
}

export interface Author {
    name:     string;
    lastname: string;
}

export interface Item {
    id:            string;
    title:         string;
    price:         Price;
    picture:       string;
    condition:     string;
    free_shipping: boolean;
    description:   string;
}

export interface Price {
    currency: string;
    amount:   number;
    decimals: number;
}
